### ISSUE TITLE
Add a workflow to build the book

### ISSUE THREAD

**Issue by MHenderson** [MHenderson/room#226]
Can we add a link to the resulting PDF in the README?

Instead of using the existing Makefile targets, it probably makes sense to create new targets just for building as part of a workflow.

**Comment by MHenderson** [comment]
First add an install target to the Makefile:
```
sudo apt install texlive texlive-science texlive-latex-extra latexmk
```

**Comment by MHenderson** [comment]
https://github.com/marketplace/actions/publish-markdown-as-pdf

**Comment by MHenderson** [comment]
I used to use this workflow:

```
name: Build LaTeX document

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: room.tex
          latexmk_use_xelatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: room.pdf
          path: room.pdf
```
